### ISSUE TITLE
userCredential issue

### ISSUE THREAD

**Issue by singhprabhanshu** [payu-intrepos/payu-core-pg-react#1]
Even passing the user credential in the makePayment method, its providing this error

request data for makePayment method is : {
  "amount": "1",
  "cardNumber": "45017209*****",
  "cvv": "***",
  "email": "********",
  "environment": "Production",
  "expiryMonth": "02",
  "expiryYear": "2029",
  "firstName": "Testing Name",
  "furl": "https://payu-react.herokuapp.com/index.php",
  "hash": "**********",
  "isSandbox": false,
  "key": "3TnMpV",
  "merchantKey": "3TnMpV",
  "nameOnCard": "test name",
  "paymentType": "Credit / Debit Cards",
  "phone": "9444444444",
  "productInfo": "Mobile Phone",
  "subventionAmount": "",
  "surl": "https://payu-react.herokuapp.com/index.php",
  "txnId": "1653631403164payusdk",
  "udf1": "",
  "udf10": "",
  "udf2": "",
  "udf3": "",
  "udf4": "",
  "udf5": "",
  "udf6": "",
  "udf7": "",
  "udf8": "",
  "udf9": "",
  "userCredentials": "3TnMpV:94444444444"
}
![5050d73c-8f5c-4595-92ff-7eff27c44ff0](https://user-images.githubusercontent.com/25033083/170642350-99c043cb-008d-45ba-a2da-90d11d65c8f4.jpeg)

**Comment by ShubhGar** [comment]
Hi
please replace "userCredentials": "3TnMpV:94444444444" to "userCredential": "3TnMpV:94444444444"

**Comment by purellarohith** [comment]
Hi @ShubhGar is there any documentation for payu-core-pg-react. Thanks

**Comment by ShubhGar** [comment]
@purellarohith, please connect with integration team “[mobile.integration@payu.in](mailto:mobile.integration@payu.in)“.
